#!/bin/bash
# Generated by ecu150v2-rauc.inc at do_install (sed replaces @RAUC_SYSTEM_COMPATIBLE@)
set -e

# 1. Parse root device from /proc/cmdline, strip the partition suffix (pN) to get the base device.
ROOT_DEV=$(grep -oP 'root=/dev/\K[^ ]+' /proc/cmdline | sed 's/p[0-9]*$//')

case "${ROOT_DEV}" in
    mmcblk0)
        DEVICE=/dev/mmcblk0
        SLOT0_DEV=/dev/mmcblk0p1
        SLOT1_DEV=/dev/mmcblk0p2
        DATA_DEV=/dev/mmcblk0p3
        ;;
    mmcblk1)
        DEVICE=/dev/mmcblk1
        SLOT0_DEV=/dev/mmcblk1p1
        SLOT1_DEV=/dev/mmcblk1p2
        DATA_DEV=/dev/mmcblk1p3
        ;;
    *)
        echo "rauc-setup-env: unknown boot device '${ROOT_DEV}'" >&2
        exit 1
        ;;
esac

# 2. Mount /data (persistent partition shared by both A/B slots).
mkdir -p /data
if ! mountpoint -q /data; then
    mount -t ext4 "${DATA_DEV}" /data
fi

# 3. Generate /etc/fw_env.config dynamically (single env copy; offset/size match NXP defconfig defaults).
cat > /etc/fw_env.config <<EOF
# Auto-generated by rauc-setup-env.service
# Device       Offset       Env size     Flash sector size  Number of sectors
${DEVICE}      0x700000     0x4000       0x10000            1
EOF

# 4. Generate /etc/rauc/system.conf dynamically.
cat > /etc/rauc/system.conf <<EOF
# Auto-generated by rauc-setup-env.service
[system]
compatible=@RAUC_SYSTEM_COMPATIBLE@
bootloader=uboot
bundle-formats=@RAUC_BUNDLE_FORMATS@
statusfile=/data/rauc.status
data-directory=/data/rauc

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=${SLOT0_DEV}
type=ext4
bootname=A

[slot.rootfs.1]
device=${SLOT1_DEV}
type=ext4
bootname=B
EOF

# 5. Marker file for quick debug verification.
touch /data/.rauc-env-configured